name = "NIfTI"
uuid = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
version = "0.4.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
GZip = "0.5"
MappedArrays = "0.2"

[extras]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GZip", "Test"]
